name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: actions-goveralls
      uses: shogo82148/actions-goveralls@v1.2.2
      with:
        # Coveralls uses this token to verify the posted coverage data on the repo and create a new check based on the results.
        github-token: ${{ github.token }}
